### ISSUE TITLE
加载`XSharedPreferences`导致`IllegalMonitorStateException`

### ISSUE THREAD

**Issue by xunmod** [canyie/pine#80]
我把梦境的`top.canyie.pine:enhances`bump到0.1.0，然后核心破解就寄了
```
E/PineXposed(  823):     Failed to load class toolkit.coderstory.com.toolkit.CorePatch from module /data/app/com.coderstory.toolkit-1/base.apk :
E/PineXposed(  823): java.lang.IllegalMonitorStateException: object not locked by thread before notify()
E/PineXposed(  823): 	at java.lang.Object.notifyAll(Native Method)
E/PineXposed(  823): 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:184)
E/PineXposed(  823): 	at de.robv.android.xposed.XSharedPreferences.$r8$lambda$0QH9w2nv1JamLFICdY8iCNFcQxg(XSharedPreferences.java)
E/PineXposed(  823): 	at de.robv.android.xposed.XSharedPreferences$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/PineXposed(  823): 	at de.robv.android.xposed.XSharedPreferences$Loader$-CC.lambda$static$0(XSharedPreferences.java:46)
E/PineXposed(  823): 	at de.robv.android.xposed.XSharedPreferences$Loader$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/PineXposed(  823): 	at de.robv.android.xposed.XSharedPreferences.startLoadFromDisk(XSharedPreferences.java:132)
E/PineXposed(  823): 	at de.robv.android.xposed.XSharedPreferences.<init>(XSharedPreferences.java:93)
E/PineXposed(  823): 	at toolkit.coderstory.com.toolkit.XposedHelper.<init>(XposedHelper.java:9)
E/PineXposed(  823): 	at toolkit.coderstory.com.toolkit.CorePatch.<init>(CorePatch.java:20)
E/PineXposed(  823): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/PineXposed(  823): 	at java.lang.Class.newInstance(Class.java:1606)
E/PineXposed(  823): 	at top.canyie.pine.xposed.PineXposed.loadOpenedModule(PineXposed.java:103)
E/PineXposed(  823): 	at top.canyie.dreamland.core.Dreamland.loadXposedModules(Dreamland.java:166)
E/PineXposed(  823): 	at top.canyie.dreamland.core.Dreamland.prepareModulesFor(Dreamland.java:123)
E/PineXposed(  823): 	at top.canyie.dreamland.Main$3.afterCall(Main.java:282)
E/PineXposed(  823): 	at top.canyie.pine.Pine.handleCall(Pine.java:766)
E/PineXposed(  823): 	at top.canyie.pine.entry.Arm64Entry.handleBridge(Arm64Entry.java:158)
E/PineXposed(  823): 	at top.canyie.pine.entry.Arm64Entry.voidBridge(Arm64Entry.java:23)
E/PineXposed(  823): 	at com.android.internal.os.ZygoteInit.startSystemServer(ZygoteInit.java:676)
E/PineXposed(  823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
```
在https://github.com/canyie/pine/commit/f65b03270cd2acb6f106f10f6ae05755dfae7a2d 之前貌似没有这个问题。我是java小白，查资料这样乱改了一下
```patch
diff --git a/xposed/src/main/java/de/robv/android/xposed/XSharedPreferences.java b/xposed/src/main/java/de/robv/android/xposed/XSharedPreferences.java
index 34e1e0a..e276b12 100644
--- a/xposed/src/main/java/de/robv/android/xposed/XSharedPreferences.java
+++ b/xposed/src/main/java/de/robv/android/xposed/XSharedPreferences.java
@@ -181,7 +181,9 @@ public final class XSharedPreferences implements SharedPreferences {
                } else {
                        mMap = new HashMap<>();
                }
-               notifyAll();
+               synchronized (this) {
+                       notifyAll();
+               }
        }
 
        /**
```
然后竟然好了。。不知道这样搞正确不正确
安卓LMY47D, arm64

**Comment by canyie** [comment]
我的锅，没注意到还有这茬。。。明天修
